# Generated by Django 4.2.1 on 2023-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_bet_db_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet_db',
            name='bet',
            field=models.CharField(max_length=50),
        ),
    ]
