# Generated by Django 4.2.4 on 2023-09-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_alter_balance_db_user_alter_bet_db_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_db',
            name='live_bet',
            field=models.BooleanField(default=False),
        ),
    ]
