# Generated by Django 4.2.4 on 2023-09-18 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0008_bet_db_live_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_db',
            name='id',
        ),
        migrations.AlterField(
            model_name='balance_db',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
